### ISSUE TITLE
搜索引擎列表可以添加自定义的么？

### ISSUE THREAD

**Issue by Sostay** [solobat/Steward#11]
![snipaste20171122_231839](https://user-images.githubusercontent.com/6897274/33134842-be120054-cfdb-11e7-9a39-c04355d6297d.png)
这个搜索引擎还可以添加么？
第一次用还不太熟悉 我想替代掉我之前的一个插件
![snipaste20171122_231900](https://user-images.githubusercontent.com/6897274/33134893-e16b332c-cfdb-11e7-8b31-13570f7726f1.png)

**Comment by solobat** [comment]
这个可以有，记下来了，之后的版本会更新这块儿

**Comment by Sostay** [comment]
感谢~

**Comment by Sostay** [comment]
另外 我感觉这个搜索框是不是可以缩小一点 目前的size看着像触控界面一样

**Comment by solobat** [comment]
搜索框这个我看看，不过最多只会做成可设置的

**Comment by Sostay** [comment]
嗯 可设置的话就挺好～

**Comment by solobat** [comment]
v3.1.1版已经添加了搜索引擎自定义的功能
具体看视频：http://v.youku.com/v_show/id_XMzE4NTk1NzkwNA==.html?spm=a2hzp.8244740.0.0
size的问题我记下了，或者另起issue也行，这个我先关了
