### ISSUE TITLE
如何解除被屏蔽（bk）的网址

### ISSUE THREAD

**Issue by nameryan** [solobat/Steward#14]
不小心敲了 bk www.abc.com
如何解除？ 在plugs列表里没找到命令。

**Comment by solobat** [comment]
没有query的时候，选中某个网址，Enter/Click就解除了。
这种操作在Steward里很常见，习惯就好。
![Imgur](https://i.imgur.com/1GPSOAl.png)

**Comment by nameryan** [comment]
操作方式还是有点费解：）
