### ISSUE TITLE
请问，可以不设置新标签页吗？

### ISSUE THREAD

**Issue by xfcdxg** [solobat/Steward#15]
作者好~！

插件很好，很实用，还在摸索阶段。但，新标签页的确太丑了。

最好能做个开关，来配置新标签页功能的显示和关闭。

推荐参考一下 Unsplash Instant、Start Today 这两个插件的展现形式。

另外，在mbp13寸下新标签页的壁纸显示有问题，下面会多出一条。

望采纳~！

**Comment by solobat** [comment]
之前一直没找到怎么设置。

不过你可以安装 Browser Alfred，跟 Steward 功能完成同步，除了新标签页。

**Comment by solobat** [comment]
看了下 Unsplash Instant，那样的形式也好加，如果 Browser Alfred 不满足的话，我之后在 Steward 上也加这样的功能。

**Comment by xfcdxg** [comment]
嗯，我试试Browser Alfred~谢啦！

**Comment by solobat** [comment]
对了
> 另外，在mbp13寸下新标签页的壁纸显示有问题，下面会多出一条。

这个问题，麻烦截图贴出来看看，我这边也是 mbp13, 不过没这情况

**Comment by xfcdxg** [comment]
![image](https://user-images.githubusercontent.com/16435465/33464968-3713ba24-d680-11e7-9cb5-3064ffb062eb.png)

**Comment by nameryan** [comment]
![image](https://user-images.githubusercontent.com/4004271/33465145-14cab584-d681-11e7-94e0-df5df9050e4c.png)

这应该只是背景图的布局问题吧

**Comment by xfcdxg** [comment]
你这是ipad吗？还是竖屏显示器？ @nameryan

**Comment by solobat** [comment]
发布了v3.1.4，背景图片优化了一下。
另外
> 最好能做个开关，来配置新标签页功能的显示和关闭

换了种形式，可以控制默认不显示**功能区**，不过没有 UI 上的开关，
在 New Tab 控制台设置下：`window.localStorage.visibleOnlyFocued = 1;`
要取消的话设置：`window.localStorage.visibleOnlyFocued = ''`就行
如果大家感觉还行的话，以后再加上 UI 设置按钮
