### ISSUE TITLE
运行插件，笔记管理及plugins开关

### ISSUE THREAD

**Issue by Edenharder** [solobat/Steward#16]
Steward 这样一个插件很棒，有三个需求：

# 运行插件

对于已经启用(处于‘on’状态)的Chrome插件，我们可以点击图标或用快捷键去运行。怎么用Steward去运行插件呢？
比如插件Atomic，希望能在Steward中输入类似`run atomic`之类的命令来运行。这样可以省去设置快捷键或每次点击插件图标的麻烦。

# 笔记管理

能否添加一个笔记的管理页面？至少添加可以删除笔记的命令。

# plugins开关

如果不需要一个plugin如Calculator或youdao，能否提供将其删除或关闭的选项？

**Comment by solobat** [comment]
1. 只能运行应用，比如 `run pocket`。如果要执行扩展的某个功能的话，需要对应扩展有暴露 api 才行，但这一般不现实，除非你去给开发者提 issue。比如我的另一个扩展[单词小卡片](https://github.com/solobat/wordcard)就是可以被 Steward 命令操控的。

2. 我加一个 `notedel` 的命令吧

3. 这个在计划中，不过可能要晚些，请关注~

**Comment by solobat** [comment]
> 能否添加一个笔记的管理页面？至少添加可以删除笔记的命令。

[v3.1.8](http://oksteward.com/steward-document-zh/plugins/browser/Note.html) 版加了这个功能，添加了`notes`命令，`shift + enter`时可以删除

**Comment by solobat** [comment]
第3点我另起一个 issue，这个先关了。
