### ISSUE TITLE
建议： new Tab 功能可开关

### ISSUE THREAD

**Issue by Hellowor1d** [solobat/Steward#17]
今天试用了下 Steward 功能，👍 作为效率工具还是很不错的，谢谢作者~:smile:
但是发现和自己在用的 new  tab 插件冲突了，所以有了这个想法

**Comment by solobat** [comment]
New Tab 都是独占的，建议你先看下这个 [Steward 攻略 -- 三种模式各有神通](https://sspai.com/post/42121)

如果确定不需要的话，可以左转去安装 [Browser Alfred](https://chrome.google.com/webstore/detail/jglmompgeddkbcdamdknmebaimldkkbl)，跟 Steward 是同源的，除了 New Tab 以外。
