### ISSUE TITLE
any way to change source of wallpaper?

### ISSUE THREAD

**Issue by dearj698** [solobat/Steward#19]
the wallpaper stays in a list of 4 and never changed , any way to change the source?
A better source than BING will be unsplash.com, I highly suggest that
and also , if possible , can you please add the function of setting up the wallpaper from local
sincerely

**Comment by solobat** [comment]
I will try to use the api of unsplash.com. If no problem,  a configuration item will be added to set the wallpaper source.

**Comment by solobat** [comment]
v3.1.11 release
> Wallpaper can be added by link;

unsplash api has some limitations, so I cannot use it in steward.

![Imgur](https://i.imgur.com/CTSaYZ1.png)

**Comment by solobat** [comment]
v3.2 add unsplash source
