### ISSUE TITLE
search 不好用，建议修改一下

### ISSUE THREAD

**Issue by meiminjun** [solobat/Steward#20]
我觉得那个search 的不好用，新手不小心enter 就直接删除了，然后我再想设置又没有搜索引擎的配置说明

**Comment by solobat** [comment]
都有提示语的吧，search 是按插件的形式做的，因此不会有 UI 设置界面的。至于容易误删，可以加个 confirm 弹窗。
另外，文档在[这里](http://oksteward.com/plugins/browser/Search.html)。

**Comment by solobat** [comment]
v3.1.11 优化了一下

删除搜索引擎前会有 confirm 提示，删除后会自动把搜索引擎的格式字符串复制到剪切板。
