### ISSUE TITLE
这么好的插件既然今天才知道.作者你太懒了.不推广推广啊

### ISSUE THREAD

**Issue by eluotao** [solobat/Steward#22]
这个插件太棒了..完全是插件版Alfred啊...很方便....特别是便笺方面我太喜欢了
收藏的网站一下就出来了,都不用我再去收藏夹点来点去了.

**Comment by solobat** [comment]
哈哈，以前是自己用得爽。
不会推广呀，求教！你也可以加入 [Telegram 频道](https://t.me/chromesteward) 传授一波~
