### ISSUE TITLE
网址输入

### ISSUE THREAD

**Issue by jacksparrowFF2** [solobat/Steward#24]
如题，在 Chrome 中输入网址时 类似于 sspai。com 的时候会自动将 。转换为 . 可否在拓展中也实现这个功能？虽然不是必须，但是如果有的话会更好，谢谢！

**Comment by solobat** [comment]
V4.1.0 已支持
![image](https://user-images.githubusercontent.com/1894203/101511783-ada3f780-39b5-11eb-99e7-9c1ce083d18c.png)
