### ISSUE TITLE
Give the ability to disable random wallpaper from Internet

### ISSUE THREAD

**Issue by piglei** [solobat/Steward#25]
Some users(like me) may not like the random wallpaper, because sometimes some random wallpaper can make the text input barely visible.

Considering this, can we add an option called "Enable random wallpaper"? if user uncheck that option, Steward will use a default wallpaper instead of a random wallpaper from the Internet.

Is this feature sounds reasonable? I would love to contribute a pull request if this purpose is accepted.

**Comment by solobat** [comment]
I think this proposal is no problem, so welcome to contribute
