### ISSUE TITLE
关于New Tab 功能

### ISSUE THREAD

**Issue by wsry888** [solobat/Steward#27]
可以给New Tab 功能做个开关不？New Tab可以用其他更好的扩展，但是快捷操作啥的就可以用Steward；这样方便些，谢谢。

**Comment by solobat** [comment]
可以使用[Browser Alfred](https://chrome.google.com/webstore/detail/browser-alfred-a-command/jglmompgeddkbcdamdknmebaimldkkbl)，除了 New Tab，其它功能一样的。
