### ISSUE TITLE
Browser Alfred 快捷键没反应的.......

### ISSUE THREAD

**Issue by jjeejj** [solobat/Steward#28]
在mac下Browser Alfred 扩展的快捷键`command + k`和 `command + j`是没有反应的.....

对于Steward 扩展快捷键是有反应的

**Comment by solobat** [comment]
可能是快捷键冲突了，禁用下 Steward，然后重新手动再设置下  Browser Alfred 的快捷键试试。

**Comment by jjeejj** [comment]
@solobat  Steward已经禁用了，Browser Alfred 快捷键 的设置地方没有找到
![jietu20180329-164944](https://user-images.githubusercontent.com/15176971/38079506-a2617eee-3371-11e8-96d1-1e2f033d0aa5.png)

**Comment by solobat** [comment]
快捷键的设置不在扩展的页面里，你看下这个帖子：http://bbs.oksteward.com/topic/5a4c77c90f590c684784a3b1

**Comment by jjeejj** [comment]
@solobat   懂了懂了，找到扩展方式设置的地方了
