### ISSUE TITLE
:) other people on twitter is doing the same thing

### ISSUE THREAD

**Issue by 1c7** [solobat/Steward#29]
https://twitter.com/ndethore/status/987191529209905154

![image](https://user-images.githubusercontent.com/1804755/39035324-280fdaf4-44ac-11e8-9bbf-3f765cba63f1.png)

**Comment by solobat** [comment]
Thanks for your introduction to Steward~

Another: https://github.com/cliffordfajardo/cato

**Comment by 1c7** [comment]
@solobat good to know Cato exist too, Thanks for telling me
