### ISSUE TITLE
[Feature Request] Provides some global variables in workflow

### ISSUE THREAD

**Issue by hiberabyss** [solobat/Steward#30]
It will be more convenient if there could be some global variables such as `title` and `url` of current page.

Thanks!

**Comment by solobat** [comment]
I think I can develop a plugin called `current` to provide this information.

**Comment by hiberabyss** [comment]
@solobat  Great to hear it! Thanks!

**Comment by solobat** [comment]
In Steward's page mode, when you use commands such as `bm` / `bk` / `his`, you can type `/` to autocomplete the current page's url.

**Comment by solobat** [comment]
Oh, sorry, I think I didn't understand what you mean at first, but just because of this I refactored the websites feature and provided some common information about the page, the trigger is `'`. 
![Imgur](https://i.imgur.com/CiMsTf7.png)

Maybe I can provide variables in the workflow, but I'm curious how you would use it.

**Comment by hiberabyss** [comment]
Cool! Thanks for your quick response.

With workflow, I would like to open some urls which use current page's url and title as the parameters.

**Comment by solobat** [comment]
Sounds OK, I will develop it later.

**Comment by solobat** [comment]
Support from v3.6

Can be used in **page mode**

### Usage
```
{{var}}
```
Global variable provided
```
{
    title,
    shortTitle,
    selection,
    icon,
    url,
    host,
    pathname,
    baseURL,
    search,
    hash
}
```

### Examples
- Search with selected text
![Search with selected text](https://user-images.githubusercontent.com/1894203/49336626-e9768a80-f640-11e8-895a-35fc6e92730f.png)

- Open related bookmarks
![image](https://user-images.githubusercontent.com/1894203/49336658-9ea94280-f641-11e8-91d4-3405f8ddc898.png)

**Comment by seancojr** [comment]
> Oh, sorry, I think I didn't understand what you mean at first, but just because of this I refactored the websites feature and provided some common information about the page, the trigger is `'`.
> ![Imgur](https://camo.githubusercontent.com/ee7035b571121a26afeba3c982201c8b00b7d9ce/68747470733a2f2f692e696d6775722e636f6d2f43694d735466372e706e67)
> 
> Maybe I can provide variables in the workflow, but I'm curious how you would use it.

In the screenshot you show creating a short URL. Can you share how you did that?

**Comment by solobat** [comment]
This feature has been removed due to the limitations of the third-party api. I can implement this function with another api.
