### ISSUE TITLE
能否支持收趣

### ISSUE THREAD

**Issue by goldenages1989** [solobat/Steward#31]
现在pocket国内下架了，现在转向收趣了。可否支持搜索收趣，谢谢。

**Comment by solobat** [comment]
看了下官网，收趣没提供 api，所以理论上是支持不了的。你也可以咨询下他们客服。

**Comment by goldenages1989** [comment]
嗯嗯，刚才问客服了，说是目前没有公开的api，不过有规划支持~

**Comment by goldenages1989** [comment]
https://github.com/lidongchao/ShouquCloudBookmarks/blob/master/source/update.py
我看这个repo里面有个api

**Comment by solobat** [comment]
ok，我了解下，先加入开发计划

**Comment by goldenages1989** [comment]
感谢~

**Comment by goldenages1989** [comment]
还有个问题，现在tab和bookmarks都不支持拼音搜索，有可能像workflow一样支持吗？

**Comment by solobat** [comment]
tab 是支持的吧，bookmarks 不支持是因为只能用 Chrome 的 api

**Comment by goldenages1989** [comment]
嗯嗯，对的，tab是支持的。明白了，谢谢。

**Comment by solobat** [comment]
> [Steward v3.5.1 beta1 发布 -- 新增插件编辑器，编写自己的插件](http://bbs.oksteward.com/topic/5b9ccf430f590c684784a403)

v3.5.1 将支持自定义 plugin 的编写，你可以试试写下收趣的。

**Comment by goldenages1989** [comment]
感谢感谢，我已经切换到linnk上面来了，他家有专门的api，我到时候看一下。

tomasy <notifications@github.com> 于2018年9月16日周日 下午11:22写道：
