### ISSUE TITLE
toastr插件冲突

### ISSUE THREAD

**Issue by mela93** [solobat/Steward#33]
![image](https://user-images.githubusercontent.com/17722672/39683994-7e0d6380-51eb-11e8-8fd0-1b958bc1d0a3.png)
在其他网站会出现这种状态。

![image](https://user-images.githubusercontent.com/17722672/39684030-a47e68f2-51eb-11e8-8958-eab6ae768a02.png)
new tap 下正常

![image](https://user-images.githubusercontent.com/17722672/39684058-ca33678c-51eb-11e8-9bdc-9285db7c5081.png)
把 steward禁用后 其他网站就正常了

请问可以出个解决方案吗？

**Comment by solobat** [comment]
这冲突是跟你安装的某个扩展，还是你访问的网站冲突？我这儿没法复现。

**Comment by mela93** [comment]
与访问的网站冲突
我是做web开发的
这是一个插件的demo：http://foxandxss.github.io/angular-toastr/

**Comment by solobat** [comment]
看到了，我看下怎么解决哈

**Comment by mela93** [comment]
好的 麻烦你了

tomasy <notifications@github.com> 于 2018年5月7日周一 16:25写道：

**Comment by solobat** [comment]
貌似没这问题了
