### ISSUE TITLE
随机命令其实应该改为“相关提示”

### ISSUE THREAD

**Issue by kaleai** [solobat/Steward#34]
据我了解这块是根据当前网站进行的命令提示，那么其实就等于根据上下文产生的搜索建议，那么可以改名为相关提示之类的，这样方便大家理解。

**Comment by solobat** [comment]
random command 是在**新标签模式**随机应用用户定义的一组命令，与你说的不一回事儿吧。

**Comment by kaleai** [comment]
很抱歉，是我的描述问题，截图：
![image](https://user-images.githubusercontent.com/9552155/39912053-f70fef72-552f-11e8-8491-cf420fc7e665.png)

其实说的是这个功能

**Comment by solobat** [comment]
soga, 这个不叫随机命令哈，这个是 website 的功能，website 分三种，1), Steward 内置，只有知乎和 Github，2)，Steward 默认适配所有网站，3), 用户在 websites 面板自行创建的

**Comment by kaleai** [comment]
哦哦 是我理解错了
