### ISSUE TITLE
有道词典 输入无效

### ISSUE THREAD

**Issue by kaleai** [solobat/Steward#35]
出现了以下界面：

![image](https://user-images.githubusercontent.com/9552155/39952348-02d4ca66-55c7-11e8-86bb-5820bc202e67.png)

后面加空格，紧接着输入要翻译的词汇，回车后输入框消失。

想问下输入是否可以中文，是否可以输入英文。

**Comment by solobat** [comment]
有道 api 现在不让用了，准备替换成别的

**Comment by solobat** [comment]
[v3.4.7](http://bbs.oksteward.com/topic/5af9b0480f590c684784a3e6)修复了
