### ISSUE TITLE
是否支持类似alfred的web search

### ISSUE THREAD

**Issue by williamHappy** [solobat/Steward#36]
![image](https://user-images.githubusercontent.com/19304825/41644181-ed4e949a-749f-11e8-8cae-fa778539eb5b.png)

**Comment by solobat** [comment]
`se` 命令满足需求吗？

**Comment by williamHappy** [comment]
也能满足 就是感觉不如alfred命令来的舒服  😄😄

**Comment by solobat** [comment]
是因为 alfred 可以为每个 search engine 设置 trigger 吗？

**Comment by plutotree** [comment]
> `se` 命令满足需求吗？

顺便吐槽下`se`的这个编辑方式真的很麻烦，直接在选项页面提供会方便很多
另外单独提供trigger的确是一种更合适的方式，再不行的话se支持参数也可以。
比如`se bd  xxx`  `se g xxx`

**Comment by solobat** [comment]
嗯，是不方便，选项里编辑一直在计划中，肯定会在后续的版本支持的。

**Comment by no1xsyzy** [comment]
顺便接入浏览器的关键词功能吧：
![default](https://user-images.githubusercontent.com/7346170/51455323-fcc1ee80-1d83-11e9-9238-bcc32fa2dfe7.png)

**Comment by solobat** [comment]
v4.1.0 已支持可视化编辑功能；关键词功能先加入 inbox，后面再看看怎么实现方便。
![image](https://user-images.githubusercontent.com/1894203/101512236-c6aca880-39b5-11eb-8ca1-e6d37c1a2d7b.png)
