### ISSUE TITLE
页面分享貌似不起作用

### ISSUE THREAD

**Issue by williamHappy** [solobat/Steward#37]
![image](https://user-images.githubusercontent.com/19304825/41644324-500fbef6-74a0-11e8-9cd5-5c7504354380.png)

**Comment by solobat** [comment]
除了 github 和知乎不能用，这两个网站有内置的 website 配置，要使用的话需要在 Websites 面板新建一个将内置的覆盖掉，后续我看看怎么优化下这块的逻辑。

**Comment by williamHappy** [comment]
不是 ，我的意思是这个分享好像没触发一样，我输入@weibo  还是在搜索
