### ISSUE TITLE
Command `dl` for Downloads makes Chrome crash.

### ISSUE THREAD

**Issue by Maples7** [solobat/Steward#40]
macOS High Sierra Version 10.13.6
Chrome Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by solobat** [comment]
macOs && Chrome v67 too, and I have not encountered this situation yet.

**Comment by Maples7** [comment]
At any webpage, `command + j` -> input `dl` -> `return` then Chrome gets stuck and crashed.
