### ISSUE TITLE
屏蔽网站功能不彻底

### ISSUE THREAD

**Issue by water-law** [solobat/Steward#41]
After blocking the site, you can still jump through the keyword + search engine. The site is still accessible, what should I do if the user needs to block a site and work hard?

[中文]屏蔽网站后， 仍可通过关键字+搜索引擎跳转。该网站仍可正常访问， 如果用户需要屏蔽某网站从而认真工作，应该怎么办呢？

**Comment by solobat** [comment]
只要网站 url 包含你 bk 后面的字符的话都会屏蔽的。你是否可以举例一下？
