### ISSUE TITLE
访问任意网页Steward会把访问地址发送到api.t.sina.com.cn

### ISSUE THREAD

**Issue by cjoys** [solobat/Steward#42]
例如我访问 www.baidu.com 打开控制台,会发送 会将我的访问地址, 发送到api.t.sina.com.cn
https://api.t.sina.com.cn/short_url/shorten.json?source=3271760578&url_long=https%3A%2F%2Fwww.baidu.com%2F 
如果我将Steward插件关掉, 就不会发送

PS: 我下载源码但是没有搜索到 api.t.sina.com 的任何信息

如下图
卸载Steward后.png
![卸载Steward后.png](https://upload-images.jianshu.io/upload_images/2076510-1f1bf017219398ff.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

安装Steward前.png
![安装Steward前.png](https://upload-images.jianshu.io/upload_images/2076510-4a9448db957957ae.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by solobat** [comment]
这是为当前页面 url 生成短网址的功能，用的新浪的 api，不过它的证书貌似过期了，准备在 v3.4.11 去掉这功能
