### ISSUE TITLE
请问se的设置可以导出和修改吗 只能重新删除再添加吗？还在可以在配置文件中修改？

### ISSUE THREAD

**Issue by tobechenghuai** [solobat/Steward#43]

**Comment by solobat** [comment]
目前是只能删除后再添加，后续会添加插件的配置导入、导出功能

**Comment by tobechenghuai** [comment]
好的 感谢 插件挺好用的 ！

**Comment by solobat** [comment]
![image](https://user-images.githubusercontent.com/1894203/101510713-3b331780-39b5-11eb-8c44-b63babf90107.png)
V4.1.0 添加了 `se` 命令的数据可视化编辑。至于导出，后面作为单独的需求另行处理。这里先关闭了。
