### ISSUE TITLE
请问Top Sites能否增加固定网站功能？

### ISSUE THREAD

**Issue by imaomao** [solobat/Steward#44]
请问Top Sites能否增加固定网站功能？

New Tab能否增加获得焦点，清空命令功能？

搜索功能否增加搜索预测？

New Tab使用默认插件功能，需要在搜索框里手动按一下空格才能显示命令内容？

**Comment by solobat** [comment]
> 1. 请问Top Sites能否增加固定网站功能？

Chrome 目前没有提供更多的 Top Sites 接口，后续可以考虑通过插件支持下。

> 2. New Tab能否增加获得焦点，清空命令功能？

在 New Tab，按 tab 键获得焦点后，已经就全选了命令，直接输入新命令就行了；同时按 esc 键，可以清空命令。

> 3. 搜索功能否增加搜索预测？

你是指实时给出查询结果吗？如果是这样，那需要开发新的插件。v3.5.1 以后也可以自己开发插件来解决需求问题。

> 4. New Tab使用默认插件功能，需要在搜索框里手动按一下空格才能显示命令内容？

启动器通常都是 trigger + space 来触发的。

**Comment by solobat** [comment]
参考下 #55  这里提到的 URL Alias 功能，感觉应该满足你的需求
