### ISSUE TITLE
帮助文件的地址404

### ISSUE THREAD

**Issue by plutotree** [solobat/Steward#45]
`help.js`中 [帮助地址](http://oksteward.com/steward-document-zh/)
```
<a href="http://oksteward.com/steward-document-zh/" target="_blank">帮助文档</a>
```
该地址无法打开，404错误

**Comment by solobat** [comment]
下版我修复一下，正确地址在[这儿](http://oksteward.com/steward-documents/zh/)

**Comment by solobat** [comment]
v3.5.4 已修复
