### ISSUE TITLE
detach/attach tabs

### ISSUE THREAD

**Issue by wmertens** [solobat/Steward#47]
I don't have time right now to make a PR for the tabs plugin, but I wrote a quick extension to detach a tab and also to attach all tabs from a window.

The attaching doesn't always work but the detach seems ok.

This is the relevant code:

detach:
```js
     chrome.tabs.getSelected(null, t => {
        if (t.id >= 0)
	        chrome.windows.create({tabId: t.id, focused: true})
      })}
```

attach, not so great code, with deprecated calls:
```js
		chrome.windows.getLastFocused(null, ({id}) =>
          chrome.tabs.getAllInWindow(id, newTabs =>
			chrome.windows.getCurrent(({id:windowId}) =>
	          chrome.tabs.getAllInWindow(windowId, currentTabs => {
	            let i = currentTabs.length
    	        newTabs.forEach(({id: tabId}) =>
					chrome.tabs.move(tabId, {windowId, index: i++}, console.log)
				)
			  })
            )
          )
        )
```

**Comment by solobat** [comment]
Steward has now opened the [api](http://oksteward.com/steward-documents/plugins/plugins.html#plugins-in-steward), and most of the plugins will be aggregated into [this repo](https://github.com/Steward-launcher/steward-plugins). The feature you need, I will add it into the steward-plugins repo. By then, you can install it using `spm install`.

**Comment by solobat** [comment]
The plugin has been developed and uploaded to [the repository](https://github.com/Steward-launcher/steward-plugins/blob/master/plugins/windowtabs.js). You can install it using `spm install windowtabs`. The `det` / `att` commands correspond to **detach** and **attach** respectively.
