### ISSUE TITLE
添加 Firefox Quantum 支持

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [solobat/Steward#48]
相关的技术资料见：
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions

**Comment by solobat** [comment]
对于类似使用 webpack 进行编译的项目，Firefox 审核很奇葩，暂时没精力申请再次上架。
本地安装见这里，[Firefox 本地安装方法](http://bbs.oksteward.com/topic/5b61815f0f590c684784a3f8)。

**Comment by KrasnayaPloshchad** [comment]
哦，明白了，不过我发现他们有 Google 论坛，有问题可以联系他们，建议收藏。
https://www.mozilla.org/en-US/about/forums/
