### ISSUE TITLE
为 Firefox Quantum 提供自签名版

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [solobat/Steward#49]
最近发现 [HTTPS Everywhere](https://www.eff.org/https-everywhere) 在其网站上发布了自带签名的版本（用 [CRX Viewer](https://robwu.nl/crxviewer/) 可以看到 META-INF 文件夹里面有 rsa 证书），建议 Steward 尝试这种发布策略。官方也发布了指南教开发者怎么做：
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Distribution
签名成功后，打开 about:addons 以后，点击⚙ ->从文件安装附加组件就能直接本地安装 xpi，这样就又多了一个安装的捷径。

**Comment by solobat** [comment]
好的，我试一下

**Comment by solobat** [comment]
Steward V3.5.7 重新上架 Firefox
http://bbs.oksteward.com/topic/5bf3c3668863020a452f57b8
