### ISSUE TITLE
Steward Lite For Firefox

### ISSUE THREAD

**Issue by duhd1993** [solobat/Steward#50]
请问能否把Steward Lite发布到firefox？
不喜欢Newtab的主要原因是输入框破坏了背景图片。如果能够设置隐藏就好了。当然可能还是把Steward Lite发到firefox这个请求容易些。

**Comment by solobat** [comment]
Steward Lite Firefox 版不久就会发布的。

另外， Steward New Tab 也可以设置隐藏输入框

使用 `nt ` 命令，第一项设置就是你要的
![image](https://user-images.githubusercontent.com/1894203/49341963-63356500-f68f-11e8-9ce1-7c493ad7ffc3.png)

设置后，打开 New Tab，输入框默认不显示，click 一下或按 tab 键使其获得焦点后，将显示出来。
