### ISSUE TITLE
bookmarks 搜索时，是否可以同时匹配 title 和 url？

### ISSUE THREAD

**Issue by weineel** [solobat/Steward#53]
### 正常搜索如下图，是没有问题的：

![image](https://user-images.githubusercontent.com/13328625/51599409-71d72480-1f3a-11e9-86fe-647c79450de7.png)

### 输入url搜索时，找不到结果：
![image](https://user-images.githubusercontent.com/13328625/51599421-7dc2e680-1f3a-11e9-8d13-6c53e4b13e8b.png)

是有什么设置需要开启，还是暂时没有实现这个功能？

**Comment by solobat** [comment]
嗯，是不支持这功能，因为用的 Chrome 提供的 api。如果要支持的话，估计得自建缓存了。也许以后会实现。

**Comment by weineel** [comment]
你好，我查看了这部分的[实现](https://github.com/solobat/Steward/blob/fd1503c98dc88840eceb42a4454c0a062beb5441/extension/js/plugins/browser/bookmark.js#L23-L45)，想加上这个功能的，发现是使用 `fuzzaldrin-plus` 模糊匹配的，没有使用chrome 提供的api。

接着查看了 Chrome 有关 [bookmarks search 的文档](https://developer.chrome.com/extensions/bookmarks#method-search)，发现 Chrome 的 api 是支持同时匹配 title 和 url 的。

**Comment by solobat** [comment]
还是得使用 recent api，不过我优化一下，让可以搜索 title / url。

**Comment by solobat** [comment]
已经发布了，请更新至最新版 v3.6.4
