### ISSUE TITLE
不知道有没有快捷打开URL的功能

### ISSUE THREAD

**Issue by phith0n** [solobat/Steward#55]
研究了一下，好像没有快捷打开URL的功能。

比如我定义一个命令`wb`，即可打开`https://weibo.com`。现在实现的话需要用书签`bm 关键字`，如果关键字是中文，可能还要切换输入法，有点麻烦。或者书签搜索的时候，不知道能不能支持拼音。

感谢~

**Comment by solobat** [comment]
目前还没这功能，书签因为用的是 chrome 自带的 api，所以不支持拼音。

之前有打算做一个命令自动扩展的功能，比如把 `wb` 自动扩展为 `https://weibo.com`，最近有时间正好添加一下。

BTW: 像文本扩展这种功能，在 Mac 上可以借助 aText 或者 Keyboard Maestro 这类 App 来实现。

**Comment by solobat** [comment]
V3.7.1 新增了 URL alias 的功能

## 设置
格式是: `${label}空格${url}`
一行一个别名，见下图
![image](https://user-images.githubusercontent.com/1894203/54137133-0698d180-4458-11e9-8b4d-8a278afa9c75.png)

## 使用
![image](https://user-images.githubusercontent.com/1894203/54137163-157f8400-4458-11e9-8415-9cf83a200d84.png)
