### ISSUE TITLE
希望新增关闭页面模式功能

### ISSUE THREAD

**Issue by zh-impact** [solobat/Steward#56]
对于标签狂人来说，每个页面都加载一个框架，很占内存。
能否控制页面模式的关闭，或者仅在指定域名开启？

![image](https://user-images.githubusercontent.com/4338052/53500125-b0856f00-3ae4-11e9-8a2e-732884b18257.png)

**Comment by solobat** [comment]
![image](https://user-images.githubusercontent.com/1894203/53502123-6c946900-3ae8-11e9-82b1-54dfa462ac72.png)
在设置里把速度优先关掉就行

**Comment by zh-impact** [comment]
关掉了，变成按需加载，按键才会触发，暂时解决了问题
