### ISSUE TITLE
⌘+J键失效，应该怎么设置？

### ISSUE THREAD

**Issue by soloproc** [solobat/Steward#57]
RT

**Comment by solobat** [comment]
chrome://extensions/shortcuts
![image](https://user-images.githubusercontent.com/1894203/61803731-49869f00-ae65-11e9-9f8e-2c52287666cf.png)

**Comment by soloproc** [comment]
> chrome://extensions/shortcuts
> ![image](https://user-images.githubusercontent.com/1894203/61803731-49869f00-ae65-11e9-9f8e-2c52287666cf.png)

Pretty Good!
