### ISSUE TITLE
可以设置成默认就是切换 tab 或者快捷键直接呼出切换 tab 的功能吗

### ISSUE THREAD

**Issue by lonenol** [solobat/Steward#62]
因为这个是最常用的，每次都要输入 tab 很麻烦和浪费时间
可以直接在无前缀命令的里面带上 tab 的结果，也可以想 Alfred 一样，可以允许给各个功能设置独立的快捷键

**Comment by solobat** [comment]
在页面模式可以
- 步骤1
访问 chrome://extensions/shortcuts
![image](https://user-images.githubusercontent.com/1894203/71388143-13c32d80-2632-11ea-9894-3e6a82013d91.png)
- 步骤2
在设置页的「通用」选项卡下
![image](https://user-images.githubusercontent.com/1894203/71388162-22a9e000-2632-11ea-9e22-3a67c2093de3.png)

**Comment by lonenol** [comment]
了解了，多谢多谢，就是需要这个功能
