### ISSUE TITLE
Page mode shortcut blocked?

### ISSUE THREAD

**Issue by LemuelCushing** [solobat/Steward#63]
I can't seem to get the page mode to start, no matter if the shortcut I set for it.
When I press the shortcut, I see the little 'blocked cookie' appear in the address bar. Is that a clue?

Thanks!

**Comment by solobat** [comment]
It looks like you turned on the setting to block third-party cookies, which caused some errors in Steward's popup page.

**Comment by LemuelCushing** [comment]
Yep, simple enough, that solved it. Thanks! :)
Do you know if I can whitelist Steward's cookies only, instead of enabling all third-party cookies?

**Comment by solobat** [comment]
I think I can fix this by releasing a new version.

**Comment by LemuelCushing** [comment]
Fantastic! Thank you!
