### ISSUE TITLE
如何禁用 Steward 接管新标签页功能？

### ISSUE THREAD

**Issue by QIanGua** [solobat/Steward#64]
原因: 

1. 在自己电脑上Steward的新标签页打开速度有点，背景图不如 Momentum 美观。
2. 两者同时开启的话总是新标签页被 Steward 接管。

**Comment by solobat** [comment]
https://chrome.google.com/webstore/detail/jglmompgeddkbcdamdknmebaimldkkbl
这个是不带新标签页的
