### ISSUE TITLE
Let `tab` command search across all windows

### ISSUE THREAD

**Issue by dmgr** [solobat/Steward#71]
Would it be possible to `tab` command to search across all windows instead of the current one?
Maybe there could be two commands:
- `ctab` for current window tab
- `atab` for all tabs across all windows
- `tab` might be configurable to behave like `ctab` or `atab` whatever user like

**Comment by solobat** [comment]
According to your proposal, I created a new [plugin](https://github.com/Steward-launcher/steward-plugins/commit/061462498ee52284ca4dd897f536797ab597641d), you can install and use it through `spm`

### Install
`spm install tabsplus`

###  Usage
`atab `

### Feature
Search for tabs in all windows, press enter to focus the window and active that tab
