### ISSUE TITLE
根据 host 查找 userscripts无效

### ISSUE THREAD

**Issue by AnabasisXu** [solobat/Steward#74]
根据这里的介绍，安装了这个插件：
http://oksteward.com/steward-documents/zh/plugins/other/User-Scripts.html#%E5%91%BD%E4%BB%A4
在Steward 和Steward plus上都试过，无效，选中之后只能copy那个命令: 

us: 根据 host 查找 userscripts

请问是怎么回事。

**Comment by AnabasisXu** [comment]
另外发现计算器计算结果也无法复制

**Comment by solobat** [comment]
谢谢反馈，是新版导致的不兼容，将在下一版修复

abtxu <notifications@github.com> 于2021年1月5日周二 下午1:13写道：

**Comment by AnabasisXu** [comment]
非常感谢！

**Comment by solobat** [comment]
> 根据这里的介绍，安装了这个插件：
> http://oksteward.com/steward-documents/zh/plugins/other/User-Scripts.html#%E5%91%BD%E4%BB%A4
> 在Steward 和Steward plus上都试过，无效，选中之后只能copy那个命令:
> 
> us: 根据 host 查找 userscripts
> 
> 请问是怎么回事。

更新了 `plugins` 库，已经修复了，可以使用 `spm install userscript` 重新安装
