### ISSUE TITLE
功能设想：可否实现用一个快捷键调出能用上下键选择的常用命令窗口？

### ISSUE THREAD

**Issue by AnabasisXu** [solobat/Steward#75]
在chrome://extensions/shortcuts可以看到， Steward有十个快捷键可设置，分别对应十种常用功能。
但在chrome设置快捷键的局限是只能以alt或者ctr开头，那么插件一多的话很快就不够了，而且记忆也不大方便。
有没有可能只用一个快捷键调出常用命令的选择界面呢？比如，on, off, set 这是三个最常用的管理插件的命令，完全可以弹出一个框上下选择，enter来选中。这样可以省去和其他插件抢快捷键的麻烦，比如surfingkeys。

另外，管理chrome快捷键的插件目前似乎没有找到，要管理的话每次都只能打开shortcuts界面，然后寻找。如果能开发一个plugin处理这个功能就好了。

感谢！

**Comment by solobat** [comment]
`help ` 命令会列出所有命令，你试试。
