### ISSUE TITLE
功能设想：有没有可能开发一个“运行插件”的功能

### ISSUE THREAD

**Issue by AnabasisXu** [solobat/Steward#76]
有些插件的运行需要点击一下插件的图标，或者设置快捷键才能运行，例如Close download bar这个插件默认快捷键是alt+w，和我的其他快捷键冲突，只好修改一个。如果不设置快捷键，也可以把插件的图标固定在浏览器的工具栏。但工具栏空间有限，即便固定了也不容易区分，点击起来还是很麻烦。现有的插件管理工具甚至还没有一个能提供固定到工具栏这个选项。 

有没有可能开发一个“运行插件”的功能，因为现有的run命令只能运行app，而on命令无法针对已经开启的插件继续操作。

感谢！

**Comment by solobat** [comment]
这个做不到，扩展没有这种权限。
